// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodForge.Data.Migrations
{
    [DbContext(typeof(FoodForgeDbContext))]
    partial class FoodForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<int>("SpentTimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("spent_time_minutes");

                    b.Property<int>("TasteRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("taste_rating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dishes");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_dishes_profile_id");

                    b.ToTable("dishes", (string)null);
                });

            modelBuilder.Entity("DishIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<int>("DishId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dish_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("MeasurementUnit")
                        .HasColumnType("TEXT")
                        .HasColumnName("measurement_unit");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_dish_ingredients");

                    b.HasIndex("DishId")
                        .HasDatabaseName("ix_dish_ingredients_dish_id");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_dish_ingredients_ingredient_id");

                    b.ToTable("dish_ingredients", (string)null);
                });

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DishId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dish_id");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<int>("TimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_minutes");

                    b.HasKey("Id")
                        .HasName("pk_recipe_steps");

                    b.HasIndex("DishId")
                        .HasDatabaseName("ix_recipe_steps_dish_id");

                    b.ToTable("recipe_steps", (string)null);
                });

            modelBuilder.Entity("Dish", b =>
                {
                    b.HasOne("Profile", "Profile")
                        .WithMany("Dishes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dishes_profile_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DishIngredient", b =>
                {
                    b.HasOne("Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dish_ingredients_dishes_dish_id");

                    b.HasOne("Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dish_ingredients_ingredients_ingredient_id");

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RecipeStep", b =>
                {
                    b.HasOne("Dish", "Dish")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_steps_dishes_dish_id");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Dish", b =>
                {
                    b.Navigation("DishIngredients");

                    b.Navigation("RecipeSteps");
                });

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("Profile", b =>
                {
                    b.Navigation("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
